// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter
// at a random position.

// Return the letter that was added to t.

func findTheDifference(_ s: String, _ t: String) -> Character {
    var sLetterCounts = [Character: Int]()
    var tLetterCounts = [Character: Int]()
    s.forEach { letter in
        sLetterCounts[letter, default: 0] += 1
    }
    t.forEach { letter in
        tLetterCounts[letter, default: 0] += 1
    }
    for letter in t {
        if sLetterCounts[letter] == nil || sLetterCounts[letter]! < tLetterCounts[letter]! {
            return letter
        }
    }
    return t[t.startIndex]
}

print(findTheDifference("ae", "aea"))